import test from 'node:test';
import assert from 'node:assert/strict';
import {makeSeed,validateData,cashFlow,assetSummary,savingAmount,syncLinked,notices,today,dateAdd,monthAdd,weekDays} from '../model.js';
test('현금흐름에서 예상수입과 저축 이체를 중복 계산하지 않는다',()=>{const d=makeSeed();validateData(d);const f=cashFlow(d,today().slice(0,7));assert.equal(f.income,4200000);assert.equal(f.expense,1680000);assert.equal(f.saving,2000000);assert.equal(f.balance,520000);assert.equal(f.expected,450000);assert.equal(savingAmount(d,d.savings[0]),6000000);assert.equal(assetSummary(d).total,32480000)});
test('입금 처리와 재수정은 수입을 한 번만 반영한다',()=>{const d=makeSeed();const e=d.expected.find(e=>e.id==='side-income');e.date=today();e.status='received';syncLinked(d,'expected',e.id);syncLinked(d,'expected',e.id);assert.equal(d.transactions.filter(t=>t.sourceExpected===e.id).length,1);assert.equal(cashFlow(d,today().slice(0,7)).income,4650000);e.amount=500000;syncLinked(d,'expected',e.id);assert.equal(cashFlow(d,today().slice(0,7)).income,4700000);e.status='expected';syncLinked(d,'expected',e.id);assert.equal(cashFlow(d,today().slice(0,7)).income,4200000);validateData(d)});
test('판매 완료는 미판매 자산에서 제외하고 실제 판매가만 수입 반영',()=>{const d=makeSeed(),i=d.items[0];i.status='sold';i.actual=600000;i.date=today();syncLinked(d,'items',i.id);syncLinked(d,'items',i.id);assert.equal(assetSummary(d).items,2850000);assert.equal(cashFlow(d,today().slice(0,7)).income,4800000);assert.equal(d.transactions.filter(t=>t.sourceItem===i.id).length,1);i.status='selling';syncLinked(d,'items',i.id);assert.equal(assetSummary(d).items,3500000);assert.equal(cashFlow(d,today().slice(0,7)).income,4200000)});
test('알림은 중요한 미완료 일정과 달성 목표만 표시',()=>{const d=makeSeed();d.goals[0].current=12;const ns=notices(d,today());assert.equal(ns.filter(n=>n.entity==='tasks').length,2);assert.equal(ns.filter(n=>n.entity==='goals').length,1);d.tasks.find(t=>t.id==='task-2').done=true;assert.equal(notices(d,today()).filter(n=>n.entity==='tasks').length,1)});
test('손상된 백업, 음수 금액, 잘못된 날짜를 거부',()=>{const d=makeSeed();d.transactions[0].amount=-1;assert.throws(()=>validateData(d));const x=makeSeed();x.tasks[0].date='2026-02-30';assert.throws(()=>validateData(x));const g=makeSeed();g.goals[0].target=0;assert.throws(()=>validateData(g));assert.throws(()=>validateData({schemaVersion:1}));const clean=makeSeed(false);validateData(clean);assert.equal(clean.transactions.length,0)});
test('날짜 계산은 월말·윤년·연말을 처리',()=>{assert.equal(dateAdd('2026-12-31',1),'2027-01-01');assert.equal(dateAdd('2028-02-28',1),'2028-02-29');assert.equal(monthAdd('2026-12',2),'2027-02');assert.deepEqual(weekDays('2026-10-01'),['2026-09-27','2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02','2026-10-03'])});
